language: generic

notifications:
  email: false

env:
  global:
  - GH_USERNAME=niksgavalas-robot
  - secure: BaEF94yZcaYDxM301rYyg2hBIAPCQaeAZp3HvSSuRnpZc5zdwTQHq49bpOoqJSCtZIs4K573mJKIgKppQuCsrbeBMxz8oujxvwI7wfseHMqjNCvxZiGCjKR6wvGR+U+Ddqi0RJxa9jocfBSEBdq18eHvpLkd0SJiP7uOJSGJ9skVbpBqfI6rrvEAmHlGlNr48ZXzWlpZOI8ypoK+2XB35lnhOqG2J6jaLAGGZs5nYY1ToxwehUGwindbPRd4kkyykh9DP/dum6nuEYDmgiUvHL9lEiaA3ByxYA2iybzJ0624YSwLdTYtTzxmW/4M9gkO2uVB+KCwuF/L8CH8fFOxhXcriSNdRBISxwy+xidYoGWqqErLMVRx138iG/90sqzynyxCcAGXW1sa7O13LF5ySvtss0i+9j0mGnw7/OwRhiZcWcYLO56PSkjMHIKUxB0+d5XIq9RfVVRZnwc3VtMR2vG3Ktf4MO3jvtcS90l7yBjviolGNLrH2jkhVlXiAeMgLfIDbIucdqjBdAKRirvLUf59OR1eH305XLM9vBck2yJW9wlBVbbom6xAvetLXvgQ3Cuf4zzHR9dSfPoc7zRZIH3PjAG4OO/hXZwN0kFKFeP5owtUExCrvw9+VQ5PufS2bSMhGMagOfomKl5KKcC/XQ1JT4/qWZ7zPTLkkmWFt/A=

install:
- git submodule update --init --recursive
- mkdir -p $HOME/bin
- wget https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_0.57.2_Linux-64bit.tar.gz
- tar -zxvf hugo_0.57.2_Linux-64bit.tar.gz -C $HOME/bin
- export PATH=$PATH:$HOME/bin

deploy:
  provider: script
  script: scripts/publish.sh
  on:
    branch: master
